 server:
  port: 8081   # Or 9090 if you want, but keep it same everywhere

spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  retry:
    instances:
      ratingHotelService:   # matches with @Retry(name="ratingHotelService")
        max-attempts: 3
        wait-duration: 2s

spring:
  cloud:
    config:
      enabled: false   # disables Config Server search
